config/routes.rb
Rails.application.routes.draw do
  resources :missions, except: [:show] do
    get 'organizations/search', to: 'organizations#search'
  end
  resources :organizations, except: [:show]

  root 'missions#index'
end

app/models/mission.rb
class Mission < ApplicationRecord

  # Association(s):
  belongs_to :organization
  belongs_to :function
  has_and_belongs_to_many :areas
  has_and_belongs_to_many :structures
  has_and_belongs_to_many :business_markets
  has_and_belongs_to_many :market_targets
  belongs_to :region

  # Validation(s):
  validates :organization_id, presence: true
  validates :function_id, presence: true
  validates :title, presence: true

end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :set_mission, only: [:edit, :update, :destroy]

  # GET /missions
  # GET /missions.json
  def index
    @missions = Mission.includes(:organization).all
  end

  # # GET /missions/1
  # # GET /missions/1.json
  # def show
  # end

  # GET /missions/new
  def new
    @mission = Mission.new
  end

  # GET /missions/1/edit
  def edit
  end

  # POST /missions
  # POST /missions.json
  def create
    @mission = Mission.new(mission_params)

    respond_to do |format|
      if @mission.save
        format.html { redirect_to missions_url, notice: 'Mission was successfully created.' }
        format.json { render :show, status: :created, location: @mission }
      else
        format.html { render :new }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /missions/1
  # PATCH/PUT /missions/1.json
  def update
    respond_to do |format|
      if @mission.update(mission_params)
        format.html { redirect_to missions_url, notice: 'Mission was successfully updated.' }
        format.json { render :show, status: :ok, location: @mission }
      else
        format.html { render :edit }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /missions/1
  # DELETE /missions/1.json
  def destroy
    @mission.destroy
    respond_to do |format|
      format.html { redirect_to missions_url, notice: 'Mission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mission
      @mission = Mission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mission_params
      params
        .require(:mission)
        .permit!
        # .permit(:organization_id, :function_id, :title, :area_ids, :business_market_ids, :structure_ids, :market_target_ids)
    end
end

app/helpers/missions_helper.rb
module MissionsHelper

  def organizations_for_select
    @organizations_for_select ||= Organization.pluck(:name, :id)
  end

end

app/views/missions/_form.html.erb
<%= simple_form_for(@mission) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <section class="mission">
      <div class="col-7"><%= f.input :title %></div>
      <div class="col-5"><%= f.input :organization_id, collection: organizations_for_select %></div>
    </section>
    <section class="criteria">
      <div class="col-7">
        <%= f.input :function_id, collection: grouped_functions_for_select, as: :grouped_select, group_method: :functions %>
      </div>
      <!-- <p>Criteria</p> -->
      <div class="col-7"><%= f.association :areas, collection: nested_areas_for_select %></div>
      <div class="col-7"><%= f.association :business_markets, collection: nested_business_markets_for_select %></div>
      <div class="col-7"><%= f.association :structures, collection: nested_structures_for_select %></div>
      <div class="col-7"><%= f.association :market_targets, collection: nested_market_targets_for_select %></div>
      <div class="col-5"><%= f.association :region %></div>
    </section>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn-primary' %>
    <%= link_to 'Cancel', missions_path, class: 'btn btn-danger' %>
  </div>
<% end %>

app/views/missions/edit.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to 'Home', root_path %></li>
    <li class="breadcrumb-item active" aria-current="page">Edit Mission</li>
  </ol>
</nav>

<h1 class="display-4">Editing Mission</h1>

<div class="form col-10">
  <%= render 'form', mission: @mission %>
</div>

app/views/missions/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">Home</li>
  </ol>
</nav>

<p id="notice"><%= notice %></p>

<h1 class="display-4">Missions</h1>

<br />
<div><%= link_to 'New Mission', new_mission_path, class: 'btn btn-primary visited' %></div>
<br />

<table class="table table-striped table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Customer title</th>
      <th scope="col" class="centered">Creation Date</th>
      <th scope="col" class="centered">Last Update Date</th>
      <th scope="col" class="centered">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @missions.each do |mission| %>
      <tr>
        <td><%= mission.title %></td>
        <td><%= mission.organization.name %></td>
        <td class="centered"><%= mission.created_at %></td>
        <td class="centered"><%= mission.updated_at %></td>
        <td class="centered actions">
          <%= link_to icon('fas', 'search'), mission_organizations_search_path(mission) %>
          <%= link_to icon('fas', 'edit'), edit_mission_path(mission) %>
          <%= link_to icon('fas', 'trash'), mission, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%- if false #@missions.any? -%>
  <div><%= link_to 'New Mission', new_mission_path %></div>
<%- end -%>

app/views/missions/new.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to 'Home', root_path %></li>
    <li class="breadcrumb-item active" aria-current="page">New Mission</li>
  </ol>
</nav>

<h1 class="display-4">New Mission</h1>

<div class="form col-10">
  <%= render 'form', mission: @mission %>
</div>

app/views/missions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_mission_path(@mission) %> |
<%= link_to 'Back', missions_path %>