config/routes.rb
Rails.application.routes.draw do
  resources :missions, except: [:show] do
    get 'organizations/search', to: 'organizations#search'
  end
  resources :organizations, except: [:show]

  root 'missions#index'
end

app/models/organization.rb
class Organization < ApplicationRecord
  include PgSearch

  # Association(s):
  belongs_to :region, optional: true
  has_and_belongs_to_many :areas
  has_and_belongs_to_many :business_markets
  has_and_belongs_to_many :structures, join_table: 'structures_organizations'
  has_and_belongs_to_many :market_targets
  has_and_belongs_to_many :functions

  # Validation(s):
  validates :name, presence: true
  validates :name, uniqueness: true

  # Search:
  pg_search_scope :search_for, against: %i(name), using: {
    tsearch: { prefix: true, any_word: true }
  }

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]
  before_action :set_mission, only: [:search]

  PATH_VALIDATOR = /\/organizations.*(term|page)/

  # GET /organizations
  # GET /organizations.json
  def index
    search_term = params.dig(:fulltext_search, :term)
    organizations = Organization
      .includes(:region, :areas, :structures, :market_targets, :business_markets)

    organizations = organizations.search_for(search_term) if search_term

    @organizations = organizations
      .order(:name)
      .paginate(page: params[:page], per_page: 20)
  end

  # # GET /organizations/1
  # # GET /organizations/1.json
  # def show
  # end

  # GET /organizations/new
  def new
    session[:redirect_to] ||= request.referer if request.referer.match(/\/organizations.*(term|page)/)
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
    session[:redirect_to] ||= request.referer if request.referer.match(/\/organizations.*(term|page)/)
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        redirection_url = get_redirection_url

        format.html { redirect_to redirection_url, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        redirection_url = get_redirection_url
        format.html { redirect_to redirection_url, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    # puts ">"*50 + " " + request.referer.inspect
    @organization.destroy
    respond_to do |format|
      redirection_url = get_redirection_url
      format.html { redirect_to redirection_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @organization = Organization
      .includes(:areas, :market_targets, :structures, :business_markets)
      .where(id: @mission.organization_id)
      .take
    function_id = @mission.function_id

    @organizations = Organization
      .joins(:areas)
      .includes(:areas)
      .joins(:functions)
      .includes(:functions)
      .joins(:market_targets)
      .includes(:market_targets)
      .joins(:structures)
      .includes(:structures)
      .joins(:business_markets)
      .includes(:business_markets)
      .joins(:region)
      .includes(:region)
      .where(areas: { id: @organization.area_ids } )
      .where(functions: { id: @mission.function_id } )
      .where(market_targets: { id: @organization.market_target_ids } )
      .where(structures: { id: @organization.structure_ids } )
      .where(business_markets: { id: @organization.business_market_ids } )
      .where(regions: { id: @organization.region_id })
      .where.not(id: @organization.id)
      .distinct
      .paginate(page: params[:page], per_page: 20)
  end

  private

    def get_redirection_url
      if session[:redirect_to].nil? && request.referer.match?(PATH_VALIDATOR)
        request.referer
      elsif session[:redirect_to].to_s.match?(PATH_VALIDATOR)
        session.delete(:redirect_to)
      else
        session.delete(:redirect_to)
        organizations_url
      end
    end

    def set_mission
      @mission = Mission.find(params[:mission_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params
        .require(:organization)
        .permit!
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper

  def display_taxonomies(collection)
    collection.map do |element|
      "<span class='badge badge-pill badge-info'>#{element.to_label}</span>"
    end.join('&nbsp;').html_safe
  end

  def display_region_name(region)
    return '' unless region
    region.name
  end

  def search_criteria(organization_name)
    case organization_name
    when "Tiller"
      {
        areas: Area.where(id: [56]),
        business_markets: BusinessMarket.where(id: [30]),
        structures: Structure.where(id: [5, 6, 10]),
        market_targets: MarketTarget.where(id: [2, 3]),
      }
    when "Synertrade"
      {
        areas: Area.where(id: [106, 112, 117, 120, 127]),
        business_markets: BusinessMarket.where(id: [43]),
        structures: Structure.where(id: [9, 10]),
        market_targets: MarketTarget.where(id: [2]),
      }
    when "Renovation Man"
      {
        areas: Area.where(id: [61, 63, 67, 70, 69, 72]),
        business_markets: BusinessMarket.where(id: [58]),
        structures: Structure.where(id: [4, 5]),
        market_targets: MarketTarget.where(id: [2, 3]),
      }
    else
      Hash.new([])
    end
  end
end

app/views/organizations/_form.html.erb
<%= simple_form_for(@organization) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <section class="mission">
      <div class="col-7"><%= f.input :name %></div>
      <div class="col-7"><%= f.association :region %></div>
      <div class="col-7">
        <% #= f.association :functions, collection: grouped_functions_for_select, as: :grouped_select, group_method: :functions, input_html: { multiple: true } %>
      </div>
    </section>

    <section class="taxonomies">
      <div class="col-7">
        <%= f.association :areas, collection: nested_areas_for_select %>
      </div>
      <div class="col-7">
        <%= f.association :business_markets, label: 'Business Model', collection: nested_business_markets_for_select %>
      </div>
      <div class="col-7">
        <%= f.association :structures, collection: nested_structures_for_select %>
      </div>
      <div class="col-7">
        <%= f.association :market_targets, collection: nested_market_targets_for_select %>
      </div>
    </section>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn-primary' %>
    <%= link_to 'Cancel', organizations_path, class: 'btn btn-danger' %>
  </div>
<% end %>

app/views/organizations/_fulltext_search.html.erb
<%= simple_form_for :fulltext_search, method: 'get', url: organizations_url, html: { class: "form-inline" } do |f| %>
  <div class="input-group">
    <%= f.input :term, label: false, required: false %>
    <span class="input-group-btn">
      <%= f.button :button, class: 'btn-secondary' do %>
        <%= icon('fas', 'search') %>
      <% end %>
    </span>
  </div>
<% end %>

app/views/organizations/_list.html.erb
<table class="table table-striped table-bordered">
  <thead class="thead-dark">
    <tr class="m-0">
      <th scope="col" class="">Name</th>
      <th scope="col" class="centered">Region</th>
      <th scope="col" class="taxos">Area</th>
      <th scope="col" class="taxos">Business Model</th>
      <th scope="col" class="taxos">Structure</th>
      <th scope="col" class="taxos">Market Target</th>
      <th scope="col" class="centered">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr class="">
        <td class=""><%= organization.name %></td>
        <td class="centered"><%= display_region_name(organization.region) %></td>
        <td class="taxos"><%= display_taxonomies(organization.areas) %></td>
        <td class="taxos"><%= display_taxonomies(organization.business_markets) %></td>
        <td class="taxos"><%= display_taxonomies(organization.structures) %></td>
        <td class="taxos"><%= display_taxonomies(organization.market_targets) %></td>
        <td class="centered actions">
          <%= link_to icon('fas', 'edit'), edit_organization_path(organization), class: 'hang-hover visited' %>
          <%= link_to icon('fas', 'trash'), organization, method: :delete, data: { confirm: 'Are you sure?' }, redirect_to: request.referer %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= will_paginate @organizations %>

app/views/organizations/edit.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to 'Organizations', organizations_path %></li>
    <li class="breadcrumb-item active" aria-current="page">Edit Organization</li>
  </ol>
</nav>

<h1 class="display-4">Editing <%= @organization.name %></h1>

<div class="form col-10">
  <%= render 'form', organization: @organization %>
</div>

app/views/organizations/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item" aria-current="page">Home</li>
    <li class="breadcrumb-item active" aria-current="page">Organizations</li>
  </ol>
</nav>

<p id="notice"><%= notice %></p>

<h1 class="display-4">Organizations</h1>

<br />
<div class="tools row">
  <div class="new col-lg-6">
    <%= link_to 'New Organization', new_organization_path, class: 'btn btn-primary visited' %>
  </div>
  <div class="search col-lg-6">
    <%= render 'fulltext_search' %>
  </div>
</div>
<br />

<%= render 'list' %>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<div class="form col-10">
  <%= render 'form', organization: @organization %>
</div>

app/views/organizations/search.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to 'Home', root_path %></li>
    <li class="breadcrumb-item"><%= link_to "#{@mission.title}", edit_mission_path(@mission) %></li>
    <li class="breadcrumb-item active" aria-current="page">Search</li>
  </ol>
</nav>

<p id="notice"><%= notice %></p>

<h1 class="display-4"><%= "Search for #{@organization.name}" %></h1>
<br />

<div>
  <h2>Search criteria</h2>
  <% criteria = search_criteria(@organization.name) %>
  <dl>
    <dt>Areas:</dt>
    <% criteria[:areas].each do |area| %>
      <dd><span class="criterium"><%= area.to_label %></span></dd>
    <% end %>
    <dt>Business Market:</dt>
    <% criteria[:business_markets].each do |business_market| %>
      <dd><span class="criterium"><%= business_market.to_label %></span></dd>
    <% end %>
    <dt>Structure:</dt>
    <% criteria[:structures].each do |structure| %>
      <dd><span class="criterium"><%= structure.to_label %></span></dd>
    <% end %>
    <dt>Market Target:</dt>
    <% criteria[:market_targets].each do |market_target| %>
      <dd><span class="criterium"><%= market_target.to_label %></span></dd>
    <% end %>
  </dl>
</div>

<br />

<% if @organizations.any? %>
  <%= render 'list' %>
<% else %>
  <br />
  <p>
    No result found for this mission search, click
    <%= link_to 'here', edit_mission_path(@mission), class: 'return-link' %>
     to return to the mission
  </p>
<% end %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>